low_voltage new port and debug pytest
cms-tedd-ip2i/low_voltage pull request #5
Opened 2023-07-12 19:16 UTC by cdozen

- hmp.py is updated with the new port
- python-package.yml: 
         > pytest  failure: Culdn't find the low_voltage module -->  solved
         > test_mqtt.py: (key error: mqtt_host)  --> the 'MQTT_HOST' environment variable issue has been solved

2023-07-12 19:19 UTC, cdozen commented
@cbernet @ArnabPurohit , new update on low_voltage repository.

2023-07-13 08:17 UTC, cbernet requested changes

2023-07-13 08:17 UTC, cbernet commented on low_voltage/lv-HMP/hmp.py
> +        "TCPIP::192.168.1.202::5025::SOCKET"
use environment variables : 

* `LOW_VOLTAGE_HOST`
* `LOW_VOLTAGE_PORT`

2023-07-13 08:17 UTC, cbernet commented on unittests/test_mqtt.py
> +import low_voltage.mqtt as connect_to_mqtt
```python
from low_voltage.mqtt import connect_to_mqtt
```

2023-07-13 08:24 UTC, merged